### ISSUE TITLE
Some build icons are upside down

### ISSUE THREAD

**Issue by Lowdive** [imperialwinter/swiw.sdd#9]
-Build icons for Rebel Commander upgrades are upside down
-Build icons for Flag upgrades are upside down on rebels side
UNCONFIRMED FOR IMPERIALS

**Comment by Lowdive** [comment]
Confirmed issue for imperial commander upgrade build icons and flag upgrade build icons.
Upside down.

**Comment by abma** [comment]
caused by https://github.com/imperialwinter/swiw.sdd/commit/cedaa79be9a131adc1806c6e598bccdb31ddc6fe
